package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/clairBuoyant/swellhub/feedback/graph/model"
)

// FindFeedbackByID is the resolver for the findFeedbackByID field.
func (r *entityResolver) FindFeedbackByID(ctx context.Context, id string) (*model.Feedback, error) {
	fmt.Println("not implemented: FindFeedbackByID - findFeedbackByID")
	return &model.Feedback{
		ID:      "fb_1",
		Message: "Test",
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
