---
actions:
  - changed-files:
      - any-glob-to-any-file: ['.github/*']
config:
  - changed-files:
      - any-glob-to-any-file:
          - '.air.toml'
          - '.dockerignore'
          - '.editorconfig'
          - '.gitignore'
          - '.github/*'
          - 'renovate.json'
dependencies:
  - changed-files:
      - any-glob-to-any-file: ['package.json', 'package-lock.json']
docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/*', '**/*.md']
test:
  - changed-files:
      - any-glob-to-any-file: ['tests/*']
