---
version: '3'

includes:
  api:
    taskfile: .taskfiles/api.taskfile.yml
    optional: true

  noaa:
    taskfile: .taskfiles/noaa.taskfile.yml
    optional: true

  web:
    taskfile: .taskfiles/web.taskfile.yml
    optional: true

tasks:
  default:
    silent: true
    cmds:
      - task --list

  deps:
    silent: true
    cmds:
      - task: web:deps
