// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFeedback = `-- name: InsertFeedback :one
INSERT INTO feedback (
    spot_id, observed_at, conditions, computed_rating, computed_confidence,
    spot_config_version, user_rating, note
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, spot_id, observed_at, conditions, computed_rating, computed_confidence, spot_config_version, user_rating, note, created_at
`

type InsertFeedbackParams struct {
	SpotID             string
	ObservedAt         pgtype.Timestamptz
	Conditions         []byte
	ComputedRating     pgtype.Text
	ComputedConfidence pgtype.Float8
	SpotConfigVersion  pgtype.Text
	UserRating         string
	Note               pgtype.Text
}

func (q *Queries) InsertFeedback(ctx context.Context, arg InsertFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, insertFeedback,
		arg.SpotID,
		arg.ObservedAt,
		arg.Conditions,
		arg.ComputedRating,
		arg.ComputedConfidence,
		arg.SpotConfigVersion,
		arg.UserRating,
		arg.Note,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.SpotID,
		&i.ObservedAt,
		&i.Conditions,
		&i.ComputedRating,
		&i.ComputedConfidence,
		&i.SpotConfigVersion,
		&i.UserRating,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
