// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feedback struct {
	ID                 int64
	SpotID             string
	ObservedAt         pgtype.Timestamptz
	Conditions         []byte
	ComputedRating     pgtype.Text
	ComputedConfidence pgtype.Float8
	SpotConfigVersion  pgtype.Text
	UserRating         string
	Note               pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

type Observation struct {
	StationID           string
	ObservedAt          pgtype.Timestamptz
	WaveHeightM         pgtype.Float8
	DominantWavePeriodS pgtype.Float8
	AverageWavePeriodS  pgtype.Float8
	WaveDirectionDeg    pgtype.Int4
	WindDirectionDeg    pgtype.Int4
	WindSpeedMps        pgtype.Float8
	WindGustMps         pgtype.Float8
	AirTemperatureC     pgtype.Float8
	WaterTemperatureC   pgtype.Float8
	SeaLevelPressureHpa pgtype.Float8
	CreatedAt           pgtype.Timestamptz
}

type Spot struct {
	ID                 string
	Name               string
	Region             string
	Latitude           float64
	Longitude          float64
	OrientationDegrees int32
	BuoyIds            []string
	Timezone           string
	IdealSwellDirMin   int32
	IdealSwellDirMax   int32
	IdealPeriodMin     float64
	PreferredWindDir   int32
	TidePreference     string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
