// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestObservation = `-- name: LatestObservation :one
SELECT station_id, observed_at, wave_height_m, dominant_wave_period_s, average_wave_period_s, wave_direction_deg, wind_direction_deg, wind_speed_mps, wind_gust_mps, air_temperature_c, water_temperature_c, sea_level_pressure_hpa, created_at FROM observations
WHERE station_id = $1
ORDER BY observed_at DESC
LIMIT 1
`

func (q *Queries) LatestObservation(ctx context.Context, stationID string) (Observation, error) {
	row := q.db.QueryRow(ctx, latestObservation, stationID)
	var i Observation
	err := row.Scan(
		&i.StationID,
		&i.ObservedAt,
		&i.WaveHeightM,
		&i.DominantWavePeriodS,
		&i.AverageWavePeriodS,
		&i.WaveDirectionDeg,
		&i.WindDirectionDeg,
		&i.WindSpeedMps,
		&i.WindGustMps,
		&i.AirTemperatureC,
		&i.WaterTemperatureC,
		&i.SeaLevelPressureHpa,
		&i.CreatedAt,
	)
	return i, err
}

const upsertObservation = `-- name: UpsertObservation :exec
INSERT INTO observations (
    station_id, observed_at, wave_height_m, dominant_wave_period_s, average_wave_period_s,
    wave_direction_deg, wind_direction_deg, wind_speed_mps, wind_gust_mps,
    air_temperature_c, water_temperature_c, sea_level_pressure_hpa
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (station_id, observed_at) DO NOTHING
`

type UpsertObservationParams struct {
	StationID           string
	ObservedAt          pgtype.Timestamptz
	WaveHeightM         pgtype.Float8
	DominantWavePeriodS pgtype.Float8
	AverageWavePeriodS  pgtype.Float8
	WaveDirectionDeg    pgtype.Int4
	WindDirectionDeg    pgtype.Int4
	WindSpeedMps        pgtype.Float8
	WindGustMps         pgtype.Float8
	AirTemperatureC     pgtype.Float8
	WaterTemperatureC   pgtype.Float8
	SeaLevelPressureHpa pgtype.Float8
}

func (q *Queries) UpsertObservation(ctx context.Context, arg UpsertObservationParams) error {
	_, err := q.db.Exec(ctx, upsertObservation,
		arg.StationID,
		arg.ObservedAt,
		arg.WaveHeightM,
		arg.DominantWavePeriodS,
		arg.AverageWavePeriodS,
		arg.WaveDirectionDeg,
		arg.WindDirectionDeg,
		arg.WindSpeedMps,
		arg.WindGustMps,
		arg.AirTemperatureC,
		arg.WaterTemperatureC,
		arg.SeaLevelPressureHpa,
	)
	return err
}
