// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetSpot(ctx context.Context, id string) (Spot, error)
	InsertFeedback(ctx context.Context, arg InsertFeedbackParams) (Feedback, error)
	LatestObservation(ctx context.Context, stationID string) (Observation, error)
	ListSpots(ctx context.Context) ([]Spot, error)
	UpsertObservation(ctx context.Context, arg UpsertObservationParams) (int64, error)
	UpsertSpot(ctx context.Context, arg UpsertSpotParams) error
}

var _ Querier = (*Queries)(nil)
