// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spots.sql

package sqlc

import (
	"context"
)

const getSpot = `-- name: GetSpot :one
SELECT id, name, region, latitude, longitude, orientation_degrees, buoy_ids, timezone, ideal_swell_dir_min, ideal_swell_dir_max, ideal_period_min, preferred_wind_dir, tide_preference, created_at, updated_at FROM spots WHERE id = $1
`

func (q *Queries) GetSpot(ctx context.Context, id string) (Spot, error) {
	row := q.db.QueryRow(ctx, getSpot, id)
	var i Spot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Latitude,
		&i.Longitude,
		&i.OrientationDegrees,
		&i.BuoyIds,
		&i.Timezone,
		&i.IdealSwellDirMin,
		&i.IdealSwellDirMax,
		&i.IdealPeriodMin,
		&i.PreferredWindDir,
		&i.TidePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpots = `-- name: ListSpots :many
SELECT id, name, region, latitude, longitude, orientation_degrees, buoy_ids, timezone, ideal_swell_dir_min, ideal_swell_dir_max, ideal_period_min, preferred_wind_dir, tide_preference, created_at, updated_at FROM spots ORDER BY id
`

func (q *Queries) ListSpots(ctx context.Context) ([]Spot, error) {
	rows, err := q.db.Query(ctx, listSpots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spot{}
	for rows.Next() {
		var i Spot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.Latitude,
			&i.Longitude,
			&i.OrientationDegrees,
			&i.BuoyIds,
			&i.Timezone,
			&i.IdealSwellDirMin,
			&i.IdealSwellDirMax,
			&i.IdealPeriodMin,
			&i.PreferredWindDir,
			&i.TidePreference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSpot = `-- name: UpsertSpot :exec
INSERT INTO spots (
    id, name, region, latitude, longitude, orientation_degrees, buoy_ids, timezone,
    ideal_swell_dir_min, ideal_swell_dir_max, ideal_period_min, preferred_wind_dir, tide_preference
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (id) DO UPDATE SET
    name                = EXCLUDED.name,
    region              = EXCLUDED.region,
    latitude            = EXCLUDED.latitude,
    longitude           = EXCLUDED.longitude,
    orientation_degrees = EXCLUDED.orientation_degrees,
    buoy_ids            = EXCLUDED.buoy_ids,
    timezone            = EXCLUDED.timezone,
    ideal_swell_dir_min = EXCLUDED.ideal_swell_dir_min,
    ideal_swell_dir_max = EXCLUDED.ideal_swell_dir_max,
    ideal_period_min    = EXCLUDED.ideal_period_min,
    preferred_wind_dir  = EXCLUDED.preferred_wind_dir,
    tide_preference     = EXCLUDED.tide_preference,
    updated_at          = now()
`

type UpsertSpotParams struct {
	ID                 string
	Name               string
	Region             string
	Latitude           float64
	Longitude          float64
	OrientationDegrees int32
	BuoyIds            []string
	Timezone           string
	IdealSwellDirMin   int32
	IdealSwellDirMax   int32
	IdealPeriodMin     float64
	PreferredWindDir   int32
	TidePreference     string
}

func (q *Queries) UpsertSpot(ctx context.Context, arg UpsertSpotParams) error {
	_, err := q.db.Exec(ctx, upsertSpot,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.Latitude,
		arg.Longitude,
		arg.OrientationDegrees,
		arg.BuoyIds,
		arg.Timezone,
		arg.IdealSwellDirMin,
		arg.IdealSwellDirMax,
		arg.IdealPeriodMin,
		arg.PreferredWindDir,
		arg.TidePreference,
	)
	return err
}
