name: Feature Request
description: Suggest an idea for this project.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## What
          **Is your feature request related to a problem? Please describe.**
              - Clear and concise description of the problem (e.g., I'm always frustrated when [...])
  - type: markdown
    attributes:
      value: |
        ## How
          **Describe the solution you'd like**
            - Clear and concise description of what you want to happen.

          **Describe alternatives you've considered**
          - Clear and concise description of any alternative solutions or features you've considered.
  - type: markdown
    attributes:
      value: |
        ## Why
          **Additional context**
            - Add any other context or screenshots about the feature request here.
