// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Feedback struct {
	ID        string    `json:"id"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"createdAt"`
}

func (Feedback) IsEntity() {}

type FeedbackInput struct {
	Message string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}
