name: proto-linter

on:
  pull_request:
    paths:
      - 'proto/**'
      - 'buf.yaml'
      - 'buf.gen.yaml'
      - '.github/workflows/proto-linter.yml'

permissions:
  contents: read

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # v1.50.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: buf lint
      - name: Breaking change check
        run: buf breaking --against '.git#ref=refs/remotes/origin/main'
